modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
displayURL="https://modrinth.com/mod/lmps"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
logoFile="assets/${mod_id}/icon.png"

[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}.client.mixins.json"

[[mixins]]
config="${mod_id}.sodium.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
